# Generated by Django 5.2 on 2025-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile',
        ),
        migrations.AddField(
            model_name='project',
            name='sortorder',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='sortorder',
            field=models.IntegerField(default=999),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
